# SPDX-FileCopyrightText: 2026 Box3D Metal contributors
# SPDX-License-Identifier: MIT
#
# Phase 5a codegen: embed the precompiled metallib as a byte blob and/or the
# .metal sources as fallback C strings. Run with cmake -P:
#
#   cmake -DB3_METALLIB=<path or empty>
#          -DB3_MAIN=<box3d_main.metal> -DB3_CONTACT=<box3d_contact.metal>
#          -DB3_VF64=<metal_vf64_ieee.metal> -DB3_DOUBLE=0/1 -DB3_RUNTIME=0/1
#          -DB3_BLOB_OUT=<box3d_metallib_blob.h> -DB3_SRC_OUT=<metal_sources.h>
#          -P tools/embed_metal.cmake

if(NOT DEFINED B3_BLOB_OUT OR NOT DEFINED B3_SRC_OUT)
  message(FATAL_ERROR "embed_metal.cmake needs B3_BLOB_OUT and B3_SRC_OUT")
endif()

# --- blob header (precompiled library, preferred at runtime) ---
if(B3_METALLIB AND NOT B3_METALLIB STREQUAL "")
  file(READ "${B3_METALLIB}" B3_HEX HEX)
  string(LENGTH "${B3_HEX}" B3_HEX_LEN)
  math(EXPR B3_BYTE_LEN "${B3_HEX_LEN} / 2")
  # Format as 16 bytes per line to keep line lengths sane.
  set(B3_BODY "")
  set(B3_POS 0)
  while(B3_POS LESS B3_HEX_LEN)
    math(EXPR B3_END "${B3_POS} + 32")
    string(SUBSTRING "${B3_HEX}" ${B3_POS} 32 B3_CHUNK)
    string(REGEX REPLACE "([0-9a-fA-F][0-9a-fA-F])" "0x\\1," B3_CHUNK "${B3_CHUNK}")
    string(APPEND B3_BODY "\t${B3_CHUNK}\n")
    math(EXPR B3_POS "${B3_POS} + 32")
  endwhile()
  file(WRITE "${B3_BLOB_OUT}"
    "// Generated by tools/embed_metal.cmake from ${B3_METALLIB}; do not edit.\n"
    "#pragma once\n\n"
    "static const unsigned long b3_metallibBlobLength = ${B3_BYTE_LEN}UL;\n"
    "static const unsigned char b3_metallibBlob[] = {\n${B3_BODY}};\n")
else()
  file(WRITE "${B3_BLOB_OUT}"
    "// Generated by tools/embed_metal.cmake; no metallib available in this build.\n"
    "#pragma once\n\n"
    "static const unsigned long b3_metallibBlobLength = 0UL;\n"
    "static const unsigned char b3_metallibBlob[] = { 0 };\n")
endif()

# --- fallback source strings (BOX3D_METAL_RUNTIME_COMPILE path) ---
if(B3_RUNTIME)
  file(READ "${B3_MAIN}" B3_MAIN_RAW)
  file(READ "${B3_CONTACT}" B3_CONTACT_RAW)
  # Runtime-compiled sources have no header search path, so the shared ABI
  # header is inlined (the .metal files keep #include "metal_abi.h" for the
  # offline build).
  file(READ "${B3_ABI}" B3_ABI_RAW)
  string(REGEX MATCH "#if defined\\( __METAL_VERSION__ \\)\n(.*)#endif\n#else" B3_ABI_MSL "${B3_ABI_RAW}")
  set(B3_ABI_MSL "${CMAKE_MATCH_1}")
  string(REPLACE "#include \"metal_abi.h\"" "${B3_ABI_MSL}" B3_MAIN_RAW "${B3_MAIN_RAW}")
  # The ABI header is inlined once (in main); the contact part drops its include.
  string(REPLACE "#include \"metal_abi.h\"" "" B3_CONTACT_RAW "${B3_CONTACT_RAW}")
  if(B3_DOUBLE)
    file(READ "${B3_VF64}" B3_VF64_RAW)
    # box3d_main.metal includes this file textually under B3_DOUBLE_PRECISION;
    # the runtime source has no header search path, so splice the contents at
    # the include line (the offline build resolves the include itself).
    string(REPLACE "#include \"metal_vf64_ieee.metal\"" "${B3_VF64_RAW}" B3_MAIN_RAW "${B3_MAIN_RAW}")
    set(B3_MAIN_COMBINED "#include <metal_stdlib>\nusing namespace metal;\n#define B3_DOUBLE_PRECISION 1\n${B3_MAIN_RAW}")
  else()
    set(B3_MAIN_COMBINED "${B3_MAIN_RAW}")
  endif()
  string(REPLACE "\\" "\\\\" B3_MAIN_ESC "${B3_MAIN_COMBINED}")
  string(REPLACE "\"" "\\\"" B3_MAIN_ESC "${B3_MAIN_ESC}")
  string(REPLACE "\n" "\\n\"\n\"" B3_MAIN_ESC "${B3_MAIN_ESC}")
  string(REPLACE "\\" "\\\\" B3_CONTACT_ESC "${B3_CONTACT_RAW}")
  string(REPLACE "\"" "\\\"" B3_CONTACT_ESC "${B3_CONTACT_ESC}")
  string(REPLACE "\n" "\\n\"\n\"" B3_CONTACT_ESC "${B3_CONTACT_ESC}")
  file(WRITE "${B3_SRC_OUT}"
    "// Generated by tools/embed_metal.cmake from src/metal/*.metal; do not edit.\n"
    "#pragma once\n\n"
    "#pragma clang diagnostic push\n"
    "#pragma clang diagnostic ignored \"-Woverlength-strings\"\n"
    "static const char b3_metalFallbackMain[] =\n\"${B3_MAIN_ESC}\";\n"
    "static const char b3_metalFallbackContact[] =\n\"${B3_CONTACT_ESC}\";\n"
    "#pragma clang diagnostic pop\n")
else()
  file(WRITE "${B3_SRC_OUT}"
    "// Generated by tools/embed_metal.cmake; runtime compilation disabled.\n"
    "#pragma once\n")
endif()
