// SPDX-FileCopyrightText: 2026 Box3D Metal contributors
// SPDX-License-Identifier: MIT

// Shared CPU/MSL ABI for the Metal backend (Phase 5a).
// Generated by tools/extract_metal.py from metal_backend.m; do not hand-edit
// the struct layouts. Regenerate after changing either side.
#ifndef B3_METAL_ABI_H
#define B3_METAL_ABI_H
#pragma once

#if defined( __METAL_VERSION__ )
// MSL struct layouts consumed by src/metal/*.metal. Standalone structs first;
// MSL requires declaration before use.
// NOTE: tools/extract_metal.py --reorder-abi is known to drop single-line
// struct definitions (its pattern requires a newline before };). Do not use
// it; struct order here was verified by hand and by the build-time compile.
// Reserved function-constant indices for later phases (5b fast math,
// 2 compact solver, 4 hull-hull binning). No kernel reads them yet; they
// only reserve the contract.
struct V2W { float4 x, y; };
struct V3W { float4 X, Y, Z; };
struct TreeOffsets { uint offset0,offset1,offset2,padding; };
struct TreeRefitParams { uint nodeOffset,nodeCount,targetHeight,padding; };
struct BodyMoveResult {
  float qx,qy,qz,qw,px,py,pz; int bodyId;
  ulong pxBits,pyBits,pzBits,userData; uint generationWorld,padding;
};
struct BodyProperties {
  float qx, qy, qz, qw;
  float forceX, forceY, forceZ;
  float torqueX, torqueY, torqueZ;
  float invMass;
  float invInertiaLocal[9];
  float invInertiaWorld[9];
  float linearDamping, angularDamping, gravityScale;
};
struct BodyState {
  float lvx, lvy, lvz;
  float avx, avy, avz;
  float dpx, dpy, dpz;
  float qx, qy, qz, qw;
  uint flags;
};
struct BodyTransform { float qx,qy,qz,qw,px,py,pz; uint supported; ulong pxBits,pyBits,pzBits; int index; uint flags;
  float localCenterX,localCenterY,localCenterZ,sleepVelocity; };
struct BoxClipVertex { float3 position; float separation; uint feature; };
struct BoxEdgeQuery { float3 normal; float separation; uint indexA,indexB,valid; };
struct BoxManifold { float3 normal; uint pointCount; BoxClipVertex points[4]; float minSeparation; uint valid; };
struct ContactInputBootstrapParams { uint count,contactCapacity,shapeCount,bodyCount; uint prepareEligible,p0,p1,p2; };
struct ContactInputSeed { uint contactId,generation,shapeIdA,shapeIdB; };
struct ContactParams { uint offset; uint count; float invH; float contactSpeed; uint useBias; float restitutionThreshold; uint p0; uint p1; };
struct ContactTransition { uint contactGeneration,pointCount; };
struct ConvexManifoldInput {
  uint eligible,shapeIdA,shapeIdB,contactId,contactGeneration,prepareEligible; int indexA,indexB; float satSeparation; uint satCache;
};
struct FinalizeResult {
  float dpx, dpy, dpz; float qx, qy, qz, qw;
  float originX, originY, originZ;
  float positionX, positionY, positionZ;
  float sleepVelocity, maxVelocity, maxDeltaPosition;
  float invInertiaWorld[9];
};
struct FusedParams {
  uint bodyCount; float h; float maxLinearSpeed; float maxAngularSpeed;
  float gravityX, gravityY, gravityZ; uint integratePosition; uint subStepCount;
};
struct ShapeParams { uint shapeCount; float extra; uint useResidentBounds; uint p1; };
struct ShapeResult {
  uint shapeId, bodyIndex, enlarged, padding;
  float lx,ly,lz,ux,uy,uz; float flx,fly,flz,fux,fuy,fuz;
};
struct Softness { float biasRate, massScale, impulseScale; };
struct Sym2W { float4 cxx, cxy, cyy; };
struct Sym3W { float4 cxx, cxy, cxz, cyy, cyz, czz; };
struct TreeNode {
  float lx,ly,lz,ux,uy,uz; ulong categoryBits; uint child1,child2; int parent; ushort height,flags;
};
struct ConvexManifoldParams { uint contactCount; float linearSlop,speculativeDistance; uint bodyCount,previousTableCount; };
struct ConvexManifoldResult { uint eligible,touching,pointCount,inputIndex; float nx,ny,nz; uint contactGeneration;
  float p1x,p1y,p1z,separation1,p2x,p2y,p2z,separation2; uint feature1,feature2,scanOffset,contactId;
  float normalImpulse1,normalImpulse2; uint persistedBits,residentFlags;
  float friction,restitution,rollingResistance,satSeparation,tangentVelocityX,tangentVelocityY,tangentVelocityZ; uint satCache;
  float anchorB1X,anchorB1Y,anchorB1Z,anchorB1Padding,anchorB2X,anchorB2Y,anchorB2Z,anchorB2Padding;
  float p3x,p3y,p3z,separation3,p4x,p4y,p4z,separation4; uint feature3,feature4; float normalImpulse3,normalImpulse4;
  float anchorB3X,anchorB3Y,anchorB3Z,anchorB3Padding,anchorB4X,anchorB4Y,anchorB4Z,anchorB4Padding; };
struct EnlargedShapeResult { int shapeId,proxyKey; float lx,ly,lz,ux,uy,uz; };
struct FinalizeParams { uint bodyCount; float invTimeStep; uint transformCount; uint publishTransforms; };
struct FinalizeProperties {
  float localCenterX, localCenterY, localCenterZ;
  float maxExtentX, maxExtentY, maxExtentZ;
  float centerX, centerY, centerZ; int bodyId;
  ulong centerXBits, centerYBits, centerZBits;
  ulong userData; uint generationWorld,padding;
};
struct HullEdge { uint origin,twin,next,face; };
struct HullTriangle { uint index1,index2,index3,face; };
struct ImpulseParams { uint wideCount,tableCount,generation,padding; };
struct ImpulsePoint { float normalImpulse,totalNormalImpulse,normalVelocity; uint featureId; };
struct ImpulseResult { uint contactId,generation,pointCount,contactGeneration; float frictionX,frictionY,frictionZ,twistImpulse;
  float rollingX,rollingY,rollingZ,padding; ImpulsePoint points[4]; };
struct JointOverflow { uint type,index; };
struct JointParams { uint offset,count; float h,invH; uint useBias; uint p0,p1,p2; };
struct ManifoldBlock { uint exceptionCount,transitionCount,stableCount,silentCount,exceptionOffset,transitionOffset,persistenceMatches,errorFlags; };
struct ManifoldCompactParams { uint contactCount,blockCount,previousCount,previousGeneration,currentGeneration,p0,p1,p2; };
struct ManifoldSummary { ulong exceptionCount; uint transitionCount,stableCount,silentCount,errorFlags; ulong persistenceMatches; };
struct PairBlock { uint sum,flags,offset,padding; };
struct PairCandidate { int proxyId,treeType,shapeIndex,padding; };
struct PairContactSeed { int shapeIndexA,shapeIndexB; };
struct PairParams { int root0,root1,root2; uint offset0,offset1,offset2,moveCount,writeCandidates,shapeCount,pairCapacity,movedEpoch,residentMoves,filterCapacity,p0,p1,p2; };
struct PairPrefixParams { uint moveCount,candidateCapacity,candidateLimit,padding; };
struct PairQueryRecord { uint count,offset,flags; int queryShapeIndex,queryProxyKey; uint cpuFilter,cpuFilterOffset; float lx,ly,lz,ux,uy,uz; };
struct PairShape { int bodyId,sensorIndex,groupIndex; uint type; ulong categoryBits,maskBits; };
struct PairSummary { ulong totalCount; uint flags,writeFlags,cpuFilterMoveCount,padding,cpuFilterCandidateCount,directCandidateCount; };
struct Params { uint bodyCount; float h; float maxLinearSpeed; float maxAngularSpeed; };
struct PointWide {
  V3W anchorAs, anchorBs; float4 baseSeparations; float4 normalImpulses;
  float4 totalNormalImpulses; float4 normalMasses; float4 leverArms; float4 relativeVelocities;
};
struct PrepareParams { uint wideCount,tableCount; float warmStartScale,invTau; Softness contactSoftness; float padding0;
  Softness staticSoftness; uint generation; };
struct PreparePoint { float anchorAX,anchorAY,anchorAZ,separation; float anchorBX,anchorBY,anchorBZ,normalImpulse; uint featureId; };
struct QW { V3W V; float4 S; };
struct S2 { float x, y; };
struct S3 { float x, y, z; };
struct SM2 { S2 cx, cy; };
struct SM3 { S3 cx, cy, cz; };
struct SQ { S3 v; float s; };
struct SegmentResult { float3 point1,point2; float fraction1,fraction2; };
struct SetItem { ulong key; uint hash,padding; };
struct ShapeCompactParams { uint shapeCount,blockCount,p0,p1; };
struct ShapeGeometry { float point1X,point1Y,point1Z,radius; float point2X,point2Y,point2Z; int bodyId;
  uint pointOffset,pointCount,planeOffset,planeCount,triangleOffset,triangleCount,edgeOffset,edgeCount,type,supported;
  float friction,restitution,rollingResistance,rollingRadius,tangentVelocityX,tangentVelocityY,tangentVelocityZ,materialPadding; };
struct ShapeInput {
  uint bodyIndex, shapeId, type; int proxyKey;
  float p1x,p1y,p1z,radius; float p2x,p2y,p2z,margin;
  float oldLx,oldLy,oldLz,oldUx,oldUy,oldUz;
};
struct BodyW { V3W v; V3W w; V3W dp; QW dq; };
struct ContactWide {
  int indexA[4]; int indexB[4]; int pointCounts[4];
  float4 invMassA, invMassB; Sym3W invIA, invIB; V3W normal; V3W tangent1; V3W tangent2;
  V3W centerA, centerB; float4 twistMass; float4 twistImpulse; Sym2W tangentMass;
  V2W frictionImpulse; Sym3W rollingMass; V3W rollingImpulse; float4 friction;
  float4 rollingResistance; float4 tangentVelocity1; float4 tangentVelocity2;
  float4 biasRate; float4 massScale; float4 impulseScale; float4 restitution;
  ulong manifolds[4]; PointWide points[4];
};
struct ParallelJoint { int indexA,indexB; SM3 invIA,invIB; Softness softness; S3 perpAxisX,perpAxisY; SQ quatA,quatB; float maxTorque; S2 perpImpulse; uint fixedRotation; };
struct PrepareInput { uint contactId; int indexA,indexB; uint generation; ulong manifold; float friction,restitution;
  float rollingResistance,tangentVelocityX,tangentVelocityY,tangentVelocityZ;
  float twistImpulse,frictionImpulseX,frictionImpulseY,frictionImpulseZ;
  float rollingImpulseX,rollingImpulseY,rollingImpulseZ; uint contactGeneration; PreparePoint points[4]; };
struct BodyS { S3 v, w, dp, dqv; float dqs; };
struct DistanceJoint { int indexA,indexB; float invMassA,invMassB; SM3 invIA,invIB; Softness constraintSoftness;
  S3 anchorA,anchorB,deltaCenter; Softness distanceSoftness; float length,hertz,lowerSpringForce,upperSpringForce;
  float minLength,maxLength,maxMotorForce,motorSpeed; float impulse,lowerImpulse,upperImpulse,motorImpulse,axialMass; uint flags; };
struct MeshContact { ulong constraints, contact; int indexA, indexB; float invMassA, invMassB; SM3 invIA, invIB;
  Softness softness; SM3 rollingMass; float friction, restitution, rollingResistance; int manifoldCount, manifoldStart; };
struct MeshPoint { S3 rA, rB; float baseSeparation, relativeVelocity, normalImpulse, totalNormalImpulse, normalMass, leverArm; };
struct MeshManifold { MeshPoint points[4]; int pointCount; S3 normal, tangent1, tangent2, centerA, centerB;
  float twistMass, twistImpulse; SM2 tangentMass; S2 frictionImpulse; S3 rollingImpulse; float tangentVelocity1, tangentVelocity2; };
constant bool B3_DOUBLE [[function_constant( 0 )]];
constant bool B3_HALF_MATERIALS [[function_constant( 1 )]];
constant uint B3_HULL_CLASS [[function_constant( 2 )]];
constant uint B3_SUBSTEP_COUNT [[function_constant( 3 )]];
#endif
#else
// C-side ABI assertions, moved verbatim from metal_backend.m.
// Metal's native float3 is 16-byte aligned, so the shader
// deliberately uses scalar fields matching this layout.
_Static_assert( sizeof( b3BodyState ) == 56, "Metal body-state ABI changed" );
_Static_assert( offsetof( b3BodyState, angularVelocity ) == 12, "Metal body-state ABI changed" );
_Static_assert( offsetof( b3BodyState, deltaPosition ) == 24, "Metal body-state ABI changed" );
_Static_assert( offsetof( b3BodyState, deltaRotation ) == 36, "Metal body-state ABI changed" );
_Static_assert( offsetof( b3BodyState, flags ) == 52, "Metal body-state ABI changed" );
_Static_assert( B3_GYROSCOPIC_ITERATIONS == 1, "Metal fused integration must match the configured gyro iteration count" );
_Static_assert( b3_capsuleShape == 0, "Metal shader capsule type literal drifted" );
_Static_assert( b3_sphereShape == 5, "Metal shader sphere type literal drifted" );
_Static_assert( b3_shapeTypeCount == 6, "Metal shader shape-type coverage changed" );
_Static_assert( ( b3_metalPairCustomFilterBit & 0x0FFFFFFFu ) == 0, "Metal pair hazard bit overlaps shape type" );
_Static_assert( b3_lockLinearX == 0x00000001, "Metal shader body-flag literal drifted" );
_Static_assert( b3_lockLinearY == 0x00000002, "Metal shader body-flag literal drifted" );
_Static_assert( b3_lockLinearZ == 0x00000004, "Metal shader body-flag literal drifted" );
_Static_assert( b3_lockAngularX == 0x00000008, "Metal shader body-flag literal drifted" );
_Static_assert( b3_lockAngularY == 0x00000010, "Metal shader body-flag literal drifted" );
_Static_assert( b3_lockAngularZ == 0x00000020, "Metal shader body-flag literal drifted" );
_Static_assert( b3_isSpeedCapped == 0x00000100, "Metal shader body-flag literal drifted" );
_Static_assert( b3_allowFastRotation == 0x00000400, "Metal shader body-flag literal drifted" );
_Static_assert( sizeof( b3MetalBodyProperties ) == 128, "Metal body property ABI changed" );
_Static_assert( sizeof( b3MetalFinalizeProperties ) == 80, "Metal finalization-property ABI changed" );
_Static_assert( sizeof( b3MetalFinalizeResult ) == 100, "Metal finalization-result ABI changed" );
_Static_assert( sizeof( b3MetalBodyMoveResult ) == 72, "Metal body-move result ABI changed" );
_Static_assert( sizeof( b3MetalShapeInput ) == 72, "Metal shape-input ABI changed" );
_Static_assert( sizeof( b3MetalShapeAABBResult ) == 64, "Metal shape-result ABI changed" );
_Static_assert( sizeof( b3MetalEnlargedShapeResult ) == 32, "Metal enlarged-shape ABI changed" );
_Static_assert( sizeof( b3TreeNode ) == 48, "Metal tree-node ABI changed" );
_Static_assert( offsetof( b3TreeNode, categoryBits ) == 24, "Metal tree-node ABI changed" );
_Static_assert( offsetof( b3TreeNode, children ) == 32, "Metal tree-node ABI changed" );
_Static_assert( offsetof( b3TreeNode, parent ) == 40, "Metal tree-node ABI changed" );
_Static_assert( offsetof( b3TreeNode, flags ) == 46, "Metal tree-node ABI changed" );
_Static_assert( sizeof( b3MetalPairQueryRecord ) == 52, "Metal pair-record ABI changed" );
_Static_assert( sizeof( b3MetalPairCandidate ) == 16, "Metal pair-candidate ABI changed" );
_Static_assert( sizeof( b3MetalPairContactSeed ) == 8, "Metal pair-contact-seed ABI changed" );
_Static_assert( sizeof( b3MetalContactInputSeed ) == 16, "Metal contact-input-seed ABI changed" );
_Static_assert( sizeof( b3MetalContactTransition ) == 8, "Metal contact-transition ABI changed" );
_Static_assert( sizeof( b3MetalPairSummary ) == 32, "Metal pair-summary ABI changed" );
_Static_assert( sizeof( b3MetalPairBlock ) == 16, "Metal pair-block ABI changed" );
_Static_assert( sizeof( b3MetalManifoldBlock ) == 32, "Metal manifold-block ABI changed" );
_Static_assert( sizeof( b3MetalManifoldSummary ) == 32, "Metal manifold-summary ABI changed" );
_Static_assert( sizeof( b3MetalPairShape ) == 32, "Metal pair-shape ABI changed" );
_Static_assert( b3_shapeTypeCount < 0x80000000u, "Metal pair-shape type encoding exhausted" );
_Static_assert( sizeof( b3MetalConvexManifoldInput ) == 40, "Metal convex-manifold input ABI changed" );
_Static_assert( sizeof( b3MetalBodyTransform ) == 80, "Metal body-transform ABI changed" );
_Static_assert( sizeof( b3MetalConvexManifoldResult ) == 240, "Metal convex-manifold result ABI changed" );
_Static_assert( offsetof( b3MetalConvexManifoldResult, inputIndex ) == 12, "Metal manifold input-index ABI changed" );
_Static_assert( offsetof( b3MetalConvexManifoldResult, scanOffset ) == 72, "Metal manifold scan-offset ABI changed" );
_Static_assert( offsetof( b3MetalConvexManifoldResult, contactId ) == 76, "Metal manifold contact-id ABI changed" );
_Static_assert( sizeof( b3MetalHullTriangle ) == 16, "Metal hull-triangle ABI changed" );
_Static_assert( sizeof( b3MetalHullEdge ) == 16, "Metal hull-edge ABI changed" );
_Static_assert( sizeof( b3MetalFloat4 ) == 16, "Metal float4 ABI changed" );
_Static_assert( sizeof( b3MetalShapeGeometry ) == 104, "Metal shape-geometry record ABI changed" );
_Static_assert( sizeof( b3SetItem ) == 16, "Metal pair-set item ABI changed" );
_Static_assert( sizeof( b3ContactConstraintPointWide ) == 192, "Metal wide contact point ABI changed" );
_Static_assert( sizeof( b3ContactConstraintWide ) == 1696, "Metal wide contact ABI changed" );
_Static_assert( sizeof( b3ManifoldConstraintPoint ) == 48, "Metal mesh contact-point ABI changed" );
_Static_assert( sizeof( b3ManifoldConstraint ) == 308, "Metal mesh manifold ABI changed" );
_Static_assert( sizeof( b3ContactConstraint ) == 176, "Metal mesh contact ABI changed" );
_Static_assert( sizeof( b3MetalContactParams ) == 32, "Metal contact parameter ABI changed" );
_Static_assert( sizeof( b3MetalContactPreparePoint ) == 36, "Metal contact-prepare point ABI changed" );
_Static_assert( sizeof( b3MetalContactPrepareInput ) == 224, "Metal contact-prepare input ABI changed" );
_Static_assert( sizeof( b3MetalContactPrepareParams ) == 48, "Metal contact-prepare parameter ABI changed" );
_Static_assert( sizeof( b3MetalContactImpulseResult ) == 112, "Metal contact-impulse result ABI changed" );
_Static_assert( sizeof( b3MetalContactImpulseParams ) == 16, "Metal contact-impulse parameter ABI changed" );
_Static_assert( sizeof( b3MetalDistanceJoint ) == 204, "Metal distance-joint ABI changed" );
_Static_assert( offsetof( b3MetalDistanceJoint, invIA ) == 16, "Metal distance-joint ABI changed" );
_Static_assert( offsetof( b3MetalDistanceJoint, constraintSoftness ) == 88, "Metal distance-joint ABI changed" );
_Static_assert( offsetof( b3MetalDistanceJoint, anchorA ) == 100, "Metal distance-joint ABI changed" );
_Static_assert( offsetof( b3MetalDistanceJoint, distanceSoftness ) == 136, "Metal distance-joint ABI changed" );
_Static_assert( offsetof( b3MetalDistanceJoint, flags ) == 200, "Metal distance-joint ABI changed" );
_Static_assert( sizeof( b3MetalJointParams ) == 32, "Metal joint parameter ABI changed" );
_Static_assert( sizeof( b3MetalParallelJoint ) == 164, "Metal parallel-joint ABI changed" );
_Static_assert( offsetof( b3MetalParallelJoint, softness ) == 80, "Metal parallel-joint ABI changed" );
_Static_assert( offsetof( b3MetalParallelJoint, quatA ) == 116, "Metal parallel-joint ABI changed" );
_Static_assert( offsetof( b3MetalParallelJoint, fixedRotation ) == 160, "Metal parallel-joint ABI changed" );
_Static_assert( sizeof( b3MetalJointOverflow ) == 8, "Metal joint-overflow ABI changed" );
#endif // B3_METAL_ABI_H
